### ISSUE TITLE
default value for parameters can only be null

### ISSUE THREAD

**Issue by majidkarimizadeh** [mehranrasulian/laravel-zarinpal#2]
hi...
im using hosted share with php v 5.6
when i try to injecting Payment class in counstructor i getting this error...
this is bug or im miss some thing....
tnx

![error](https://user-images.githubusercontent.com/20487980/30734586-a83b90c0-9f88-11e7-9e91-8030866c5158.jpg)

**Comment by mehranrasulian** [comment]
That's because you are using PHP 5 while this package requires PHP 7.

**Comment by mehrancodes** [comment]
@majidkarimizadeh I added support for PHP 5. Ready to use :ok_hand:
